### PR TITLE
PR: Change footer

### LINKED ISSUE #113: Add Twitter and Facebook links somewhere for easy access and SEO
Currently, our Facebook and especially Twitter links aren't really linked from anywhere but our OpenCollective to my knowledge, and correspondingly have very low SEO rankings and are very hard to find. Therefore, they should be presumably added to our website somewhere for easy access for users to keep updated and stay in touch, as well as improve their tracking by search engines. Also, linking our website *from* our Twitter and Facebook probably would also be a good idea...

### PR DESCRIPTION
**Pull request by dalthviz**
A preview: 

imagen

Maybe fixes #113 (showing social links with the names instead of icons).

### CODE REVIEW

**Review by CAM-Gerlach — COMMENTED** [review]
Looks nice, but its absolutely enormous vertically for a footer just containing credits and a few social media links (most footers with these sorts of modern themes tend to contain a full sitemap), especially if the dark gray will be the actual color. Additionally:

* Main copyright statement should be ``© 2018 Spyder Website Contributors`` 
* Correct name of license for Freepik is exactly as stated previously for FreeHTML5 Template: CC-BY 3.0 , but according to my research this is not in fact the correct license
* Last line needs to be directly after the template information; it doesn't make sense on its own

To reduce the vertical size, I recommend the following:

* Greatly decrease top and bottom margin
* Greatly decrease the line spacing of everything but the "Connect with us" line
* Increase font size of connect with us line to 16px while decreasing everything else to 12 px (or ``em``/``rem`` equivalent)
* Additionally, a lot of the actual credit text is either redundant or inapplicable. After some research, removing that plus the above revisions and combining lines where possible yields the following:

© 2018 Spyder Website Contributors; licensed [MIT](https://opensource.org/licenses/MIT) | Icons by [Freepik](https://www.freepik.com/) from [Flaticon.com](https://www.flaticon.com/)
[Template](https://freehtml5.co/icon-free-website-template-using-bootstrap/) designed by [FreeHTML5.co](https://freehtml5.co/) | [Hugo](https://gohugo.io/) port by [SteveLane](https://github.com/SteveLane/) | [Lektor](https://www.getlektor.com/) port by [Dalthviz](https://github.com/dalthviz/)

**Comment by dalthviz** [comment]
A new preview with the changes:

imagen

**Comment by CAM-Gerlach** [comment]
Thanks. Sizing looks good, but the text does not appear to have been changed. Also, you could probably slightly increase the vertical space between the "Connect with us" and first copyright line, while slightly reducing it at the top and bottom of the footer itself, to better separate the two individual elements within the common footer so they don't mush together.

**Comment by ccordoba12** [comment]
> Thanks. Sizing looks good, but the text does not appear to have been changed

Text is fine for me, so I instructed @dalthviz to leave it like that.

> Also, you could probably slightly increase the vertical space between the "Connect with us" and first copyright line, while slightly reducing it at the top and bottom of the footer itself, to better separate the two individual elements within the common footer so they don't mush together.

I agree with this. @dalthviz, please work on it, so we can finish this PR.

**Comment by CAM-Gerlach** [comment]
> Text is fine for me, so I instructed @dalthviz to leave it like that.

Right, but as I explained in detail with my previous post, upon further research the existing text contains a number of unclear, redundant, or outright incorrect statements, and the layout/organization could certainly use improvement. The suggested revision mitigates or eliminates these problems, is cleaner and more concise, and communicates the same or more (correct) information. Also, it would also enable a more consistent look when re-used for the docs portion of the site, since the copyright/credit text is certainly not more than two lines there, as is the suggested revision, and unlike the four of the original. Therefore, I'm not sure I understand why it should not be used in preference to the original version.

**Comment by ccordoba12** [comment]
@CAM-Gerlach, ok, let's follow your suggestion. @dalthviz, please leave the text like this

```
© 2018 Spyder Website Contributors CC-BY 3.0
Icons by Freepik from Flaticon.com | Template designed by FreeHTML5.co
Hugo port by SteveLane | Lektor port by Dalthviz
```

with the corresponding links.

@CAM-Gerlach, content is not licensed with code licenses (like MIT), so let's use `CC-BY 3.0` for our website.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 

Okay, excellent.

I'm curious why you would want to needlessly split it into three lines? It is already tall and narrow as it is, and if a screen is smaller (some mobiles) it will just soft wrap, while adding extra lines just takes up space for no gain. Further, it disrupts the carefully adjusted flow of the original, and credit line footers typically are only a single line, or at most two, never an awkward block like that. Again, the original footer on the template was designed with a comprehensive site map in mind, not a mere credit line, which is why it is much taller than is appropriate for this use.

> CC-BY 3.0

The site as a whole is licensed MIT (Expat), as stated in the LICENSE.txt in the repo, We could relicense just the text (not a bad idea in and of itself, but well out of scope for this PR), but we'd have to get the written permission of all contributors first, and would then need to list both licenses with what they apply to (MIT for code, CC-BY for text). Furthermore, I'm not sure why we shouldn't use CC-BY 4.0 if so, since its clearer, more refined and better internationalized.

> Template designed by FreeHTML5.co
> Hugo port by SteveLane | Lektor port by Dalthviz

As a corollary to the above, again these conceptually are closely linked and thus belong in the same line, and otherwise it is unclear what the latter two statements refer to. Again, I recommend the arrangement in my previous comment unless there are clear, specific reasons articulated for why it should not be the case, as the latter has been carefully tuned for legality, clarity, correctness, and layout cleanliness.

**Comment by dalthviz** [comment]
A new preview:
imagen

**Comment by CAM-Gerlach** [comment]
@dalthviz Can you perhaps trim the top and bottom margins a little as discussed previously? And maybe even a tiny bit less line spaceing between the two blocks but that's probably getting way too nitpicky.

Also, besides the above comments on the text, there should be a space between the copyright symbol and date for readability, and the template should be linked as in the above version per the license agreement.

**Comment by dalthviz** [comment]
A new preview: 
imagen

**Comment by ccordoba12** [comment]
> I'm curious why you would want to needlessly split it into three lines?

I don't want all these copyright attributions to be wider than the *Connect with us* line.

> The site as a whole is licensed MIT (Expat), as stated in the LICENSE.txt in the repo

The license applies to the code that supports the website, not to its contents. @dalthviz, please remove the `CC-BY 3.0` link on the contributors line for now. We'll see what to do about that later.

> As a corollary to the above, again these conceptually are closely linked and thus belong in the same line

Sorry, don't like it for the reason I mentioned above. I really don't care about how logical things are but about how well they look.

----

@CAM-Gerlach, I really don't want to keep discussing over and over about these simple things. I understand your points and I think we have covered most of them here. However, we have to cut the line somewhere, and this is it: after @dalthviz removes `CC-BY 3.0`, I'll merge this PR.

@dalthviz, please also open a PR in `spyder-docs` with the new footer.

**Review by ccordoba12 — APPROVED** [review]

**Comment by CAM-Gerlach** [comment]
You're right, no need to keep haggling over such tiny things.

> I don't want all these copyright attributions to be wider than the Connect with us line.

Thanks for explaining. I'm not sure I understand why this really needs to be the case, but with that as an assumed constraint the layout you chose makes sense and is pretty much as optimal as it can be.

> We'll see what to do about that later.

Changing the website contents (text and media) to CC-BY (4.0) is actually a great idea, and would basically just require everyone who's contributed such appearing in the current site (i.e. me, you, @dalthviz , and @jitseniesen ) to state their agreement in writing somewhere (like comments on a Github issue to that effect), and then I or someone could make the minor changes to make this clear in the repo. Would you like me to create said issue?

> I really don't care about how logical things are but about how well they look.

For me, layout is important but clarity in actually communicating the information is most important. However, within the constraint of keeping lines shorter than that of the connect with us, your final choice is pretty much the best that can be done.

**Pull request merged**
