### PR TITLE
PR: Use a new theme in the home page

### PR DESCRIPTION
**Pull request by dalthviz**
[The theme](https://github.com/SteveLane/hugo-icon)
[The theme ported to lektor](https://github.com/dalthviz/hugo-icon)

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks a lot for this @dalthviz! Some questions:

1. Could post a screenshot of the site with the new theme?
2. I think we should move the adapted Hugo theme to a repo insider the spyder-ide org. What do you think?
3. Why did you add an image of yourself to the repo? I don't have a problem with that, I'm just asking :-)

**Comment by dalthviz** [comment]
@ccordoba12 

1. A preview:

prev

2. :+1:

3. Just for testing purposes :)

Also, although the template of the single-page is now used, a lot of content is missing (images, descriptions, etc.). Any feedback would be greatly appreciated @spyder-ide/core-developers @spyder-ide/junior-developers

**Comment by ccordoba12** [comment]
It's looking really good! For now please hide the links to *Documentation*, *Blog* and *Community*, so they can be ported in successive PRs. Also, please add more people to *The team*. Then, I'd say we can merge so you can keep iterating quickly.

*The description* part needs more work, but I think @CAM-Gerlach can help us with that.

**Comment by ccordoba12** [comment]
Also, please change *Overview > Components* to *Overview > Download* and add the relevant download information there.

**Comment by CAM-Gerlach** [comment]
Awesome work @dalthviz ! I'll definitely try to take a look at fleshing out the description next weekend as well as giving any additional feedback; I have several exams to prepare for this week (both that I'm writing/proctoring, and taking myself) as well as some other big volunteer commitments.

**Comment by csabella** [comment]
I agree with @ccordoba12  to get this merged so that you can iterate on the other parts.  It would be easier for me to give feedback if I can use the pages and I'm not sure how to install these changes to do that.

**Comment by CAM-Gerlach** [comment]
@csabella Did the method suggested in the readme not work to get lektor up and running?

**Comment by dalthviz** [comment]
@ccordoba12 I already did the changes, I also added a donate button, this is a preview:

prev
----------------------
@csabella about the way to see the changes you need to:
* Install lektor (I suggest to do it in a new env in conda)
```conda install lektor -c conda-forge```
* Clone the project, in this case https://github.com/dalthviz/website-spyder in the `theme` branch
* Use ```lektor server``` in the root of the project.

As @CAM-Gerlach said I think some instructions are in the README of the project. Although, if that is not working maybe we should update it.

**Comment by CAM-Gerlach** [comment]
@dalthviz Indeed, those are precisely the instructions in the README, but I haven't tried them in a while.

**Comment by dalthviz** [comment]
@ccordoba12 a preview with the latest changes:

prev

**Review by ccordoba12 — APPROVED** [review]
I really like it! Thanks @dalthviz!

**Pull request merged**
