### PR TITLE
PR: Implement minor post-theme implementation changes to the Spyder site

### LINKED ISSUE #183: Minor followup changes after implementation of new theme
* [x] Change FG color to theme default
* [x] Don't use different feature background on hover
* [x] Eliminate Spyder Reports from plugins
* [x] Fix order of donate and sponsors and nix sponsors from navbar to make it shorter
* [x] Add links to components and sponsors
* [x] ~~Reduce size of Spyder screenshot to avoid it cropping~~ Looks much too small on desktop, much more so than expected; recommend discussing this in a separate issue and addressing this in another PR by adding an abstract background (e.g. zoomed and blurred Spyder) and either reducing size as originally planned, switching to "cover" mode, and/or making the half-height breakpoint occur earlier
* [x] Change logo to raster and eliminate Blog
* [x] Copyedit mainpage text
* [x] Update screenshot in README

### PR DESCRIPTION
**Pull request by CAM-Gerlach**
Implements the relatively minor changes discussed in #183 , as agreed, to update and improve the appearance of the website following the port to Lektor-Icon v2.

This PR is ready for review and merging, now that spyder-ide/lektor-icon#14 is approved and merged and the necessary rebasing complete.

* [x] Change FG color to theme default
* [x] Don't use different feature background on hover
* [x] Eliminate Spyder Reports from plugins
* [x] Fix order of donate and sponsors and nix sponsors from navbar to make it shorter
* [x] Add links to components and sponsors
* [x] ~~Reduce size of Spyder screenshot to avoid it cropping~~ Looks much too small on desktop, much more so than expected; recommend discussing this in a separate issue and addressing this in another PR by adding an abstract background (e.g. zoomed and blurred Spyder) and either reducing size as originally planned, switching to "cover" mode, and/or making the half-height breakpoint occur earlier
* [x] Change logo to raster and eliminate Blog
* [x] Copyedit mainpage text
* [x] Update screenshot in README

Fixes #183

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
I realized nowhere on the website is it mentioned that Spyder is free or open source, so I mentioned that in the first sentence of the description.

**Review by ccordoba12 — APPROVED** [review]
Very nice improvements! Thanks @CAM-Gerlach!

**Comment by ccordoba12** [comment]
@CAM-Gerlach, what do you think about merging this one right now? It has a lot of nice improvements, and @juanis2112 and @dalthviz could open issues next week in case they don't agree with something.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 It's your call.

**Review by juanis2112 — APPROVED** [review]
I think this looks great! Thanks @CAM-Gerlach

**Pull request merged**
