### PR TITLE
PR: Decrease line height in blog and use the same style for links as in our docs

### PR DESCRIPTION
**Pull request by ccordoba12**

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
Looks good!

**Comment by ccordoba12** [comment]
Yep, agreed! Thanks for insisting on this one and sorry for being so stubborn about it.

**Comment by CAM-Gerlach** [comment]
My mom said "Yeah, its nice!" when she looked at it.

**Comment by ccordoba12** [comment]
Ok, releasing to production then.

**Comment by CAM-Gerlach** [comment]
> Thanks for insisting on this one and sorry for being so stubborn about it.

I'm pretty sure that I've been more stubborn than you, jeje, though I was close to just accepting 1.7 as a compromise given I'd already done so much disagreeing on stuff lately.

**Pull request merged**
