### PR TITLE
PR: Improvements to the single-page home

### LINKED ISSUE #65: Feedback on the new theme
Some things that are broken or I'd like to change with respect to the new theme:

1. The navbar doesn't remain fixed at the top in Firefox when you scroll down and scroll back to the  top again. It works as expected in Chrome.
2. The image with the big logo should also contain a screenshot of a full Spyder session below it and centered. Else, it seems strange that there is a huge white region below it.
3. In the *Overview* section, let's remove the images to the right and let's put *Description* and *Download* at the center of it.
4. The images in the *Components* section are not shown. That's because a `/` gets added to end of their name (e.g. `ipython.png/`). I don't know how to fix it in Lektor though.
5. There is a big blank space between *Components* and *Plugins* that should be removed.
6. We need to find a way to add links to the images of the *Plugins* section (but that can be added later).

### PR DESCRIPTION
**Pull request by dalthviz**
Fixes #65 
### TODO
- [x] Fix images of components (src url).
- [x] Update banner image.
- [x] Fixed navbar in Firefox.
- [x] Delete images of the _Overview_ section.
- [x] Delete space between _Components_ and _Plugins._
- [x] Link images in _Plugins_ section.

### CODE REVIEW

**Comment by dalthviz** [comment]
@ccordoba12 a preview:

prev

**Comment by ccordoba12** [comment]
It's looking really good @dalthviz, thanks! The only detail I don't like is the ladder organization you added in the *Plugins* section. Please make all images to be in the same row.

Other than that, I think you addressed all my issues, thanks!

**Comment by ccordoba12** [comment]
@dalthviz, is this ready?

**Comment by dalthviz** [comment]
Yep @ccordoba12 here a preview:
prev

**Review by ccordoba12 — APPROVED** [review]
Nice! Thanks a lot @dalthviz!

**Pull request merged**
