### PR TITLE
PR: Changes to the front page (new sections - download and donate)

### PR DESCRIPTION
**Pull request by dalthviz**

### CODE REVIEW

**Comment by ccordoba12** [comment]
@dalthviz, is this ready for merge?

**Comment by dalthviz** [comment]
@ccordoba12 the individual donate section (outside the footer) is missing. That is the last element to be done here.

**Comment by ccordoba12** [comment]
Ok, please let me know when that's done.

**Comment by dalthviz** [comment]
@ccordoba12 ready for merge

**Review by ccordoba12 — APPROVED** [review]

**Pull request merged**
