### PR TITLE
PR: Add gitter chat

### LINKED ISSUE #5: Add gitter chat to website
lektor-chat-example

### PR DESCRIPTION
**Pull request by rlaverde**
Fixes #5

### CODE REVIEW

**Comment by goanpeca** [comment]
Woooooohoooooooo :-)

Could you post a screenshot of how it looks so far :-p

**Comment by rlaverde** [comment]
It looks quite simple now, (I'm working in a banner from the home page)
spider website

**Comment by goanpeca** [comment]
Nice, still good to see how it looks so far :-)

**Comment by goanpeca** [comment]
LGTM merge?

**Comment by rlaverde** [comment]
> LGTM merge?

yes

**Comment by goanpeca** [comment]
@rlaverde it is called, sp**Y**der not sp**I**der

**Comment by rlaverde** [comment]
> @rlaverde it is called, spYder not spIder

Oh sorry!!  I will fix that in the PR of the banner layout

**Pull request merged**
