### PR TITLE
Test that Netlify is working

### PR DESCRIPTION
**Pull request by ccordoba12**

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
@ccordoba12 I assume whatever was going on with Netlify resolved itself?

**Comment by ccordoba12** [comment]
If I recall correctly, Netlify was broken and the fix required a config change on their side. So I opened this PR to test that.

**Comment by CAM-Gerlach** [comment]
Ah, thanks. You mean something in their admin panel? Everything should be configured repo-side and I use more or less the same config a bunch of different places and don't recall having an issue. The only thing I can think of would be the version of the build image since they just updated that, but given Netlify looked like it wasn't triggering at all, I would think that wasn't the issue. Any chance you can remember what it was? Seems important to know...

**Comment by ccordoba12** [comment]
I think it was the branch used for building the site.

**Comment by CAM-Gerlach** [comment]
Yup. Thanks!

**Pull request closed without merging**
