### PR TITLE
PR: Add docs to the navbar

### PR DESCRIPTION
**Pull request by dalthviz**

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
Just so I'm aware, should this wait on spyder-ide/spyder-docs#14 (in review), spyder-ide/spyder-docs#13 (I can do it Saturday if 14 is merged before then) and your final formatting fixes to finish off spyder-ide/spyder-docs#19 ?

**Comment by dalthviz** [comment]
I would say so :)

**Comment by CAM-Gerlach** [comment]
@dalthviz Thanks. Just FYI, while I could knock that all out this weekend in theory, given the current pace of PR approval and the discussion we're having on what to do about #14 , you might have to wait much longer. Sorry for the delay...

Also, somewhat tangential but would you like me to go ahead and make the followup minor changes I mentioned on #21 that didn't make the final merge, along with those you helped me with on Gitter (fixing the spacing issues)?

**Comment by dalthviz** [comment]
>@dalthviz Thanks. Just FYI, while I could knock that all out this weekend in theory, given the current pace of PR approval and the discussion we're having on what to do about #14 , you might have to wait much longer. Sorry for the delay...

@CAM-Gerlach no problem with that :+1: 
>...would you like me to go ahead and make the followup minor changes I mentioned on #21 that didn't make the final merge, along with those you helped me with on Gitter (fixing the spacing issues)?

For the issue of the spacing I think is ok :+1: Although, probably, we need to create a different issue to discuss the changes of the font-size in order to define the correct size for each part of the website (main, blog, docs, etc). What do you think @ccordoba12?

**Comment by CAM-Gerlach** [comment]
@dalthviz Just a reminder, you might want to also make the top bar logo/logotype (with the Title Case small caps Spyder name) use the same one as the docs, as you did (and said you'd do here) in spyder-ide/spyder-docs#21 . And thanks again for your help with the CSS for the docs!

**Comment by ccordoba12** [comment]
@dalthviz, please fix the merge conflicts in this one so we can merge it.

**Review by ccordoba12 — APPROVED** [review]
Let's merge this one to `develop` to see how it looks.

**Comment by ccordoba12** [comment]
It looks really nice! Thanks @dalthviz!

Let's wait until the footer PR is merged in `spyder-docs` before merging this with `production`.

**Pull request merged**
