### PR TITLE
PR: Basic changes to the website

### LINKED ISSUE #58: Update componets text and images

### PR DESCRIPTION
**Pull request by dalthviz**
Fixes #58

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks @dalthviz! Good to see that you were able to understand Rafa's work!

Could you post screenshots of before/after this change? Thanks!

**Comment by jitseniesen** [comment]
@dalthviz Thanks for working on the website. Having a more up-to-date website is one of our most important tasks for us, I believe. I don't have experience or feeling on how to set up the website but I am happy to write some text once the framework is there.

**Comment by dalthviz** [comment]
@ccordoba12 a preview of the changes:

#### Before:
before

### After:
after

**Review by ccordoba12 — APPROVED** [review]

**Comment by ccordoba12** [comment]
Thanks @dalthviz, keep up the good work here! :+1:

**Comment by ccordoba12** [comment]
@dalthviz, do you plan to do more things here? I say it because you left a WIP in the title :-)

**Comment by dalthviz** [comment]
Yep @ccordoba12, for the components section I want to check the size of the images to make the text show at the same level. Although if you are ok with that then I don't have more changes to do and probably we can merge this :+1:

**Comment by ccordoba12** [comment]
> for the components section I want to check the size of the images to make the text show at the same level

That seems a good addition too. Please proceed and let me know when this one is ready to be merged.

**Comment by dalthviz** [comment]
@ccordoba12 I think this is done :+1:

**Comment by ccordoba12** [comment]
Thanks @dalthviz!

**Pull request merged**
