### PR TITLE
PR: Optimize logo PNGs after they were modified in PR #199

### PR DESCRIPTION
**Pull request by CAM-Gerlach**
The various logo PNGs added in PR #199 were not optimized with `optipng`, like the originals were. Doing so resulted in them being an average of 2x smaller than they were before essentially for free, which is a significant help to reducing download bandwidth (though unfortunately the old versions are stuck in the repo indefinitely now, nothing we can do about that without rewriting history).

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
The change is trivial, but it looks like there's a problem with old deps in the build system. This should be fixed by either pulling in my updates and simplifications from uah-ams/uah-ams-website#3 (which in turn was based directly off the infra I set up here), or unpinning the Weurkzueg dep now that lektor-atom v0.4.0 _finally_ just got released 3 days ago, after well over a year of waiting. I'll go ahead with another PR to fix that first.

**Comment by ccordoba12** [comment]
> or unpinning the Weurkzueg dep now that lektor-atom v0.4.0 finally just got released 3 days ago, after well over a year of waiting

I suggest doing this, which seems simpler. But it's really up to you.

**Comment by CAM-Gerlach** [comment]
I'm not 100% sure if only one or both will be needed to fix it, but regardless it should be a straightforward fix and simplify things going forward.

**Comment by CAM-Gerlach** [comment]
This is ready now. Since it is a simple, rote image optimization, the checks pass and I verified each image appears identical to before in the build preview, going ahead and merging.

**Pull request merged**
