### PR TITLE
PR: Re-add 3.3.0 post by reverting the revert

### PR DESCRIPTION
**Pull request by CAM-Gerlach**
Reverts the revert to re-add this blog post after the Quansight video one. Repeat of #137 and revert of #140 . Revertception!

### CODE REVIEW

**Comment by ccordoba12** [comment]
I'll approve this one once new conda packages for 3.3.1 are available.

**Comment by CAM-Gerlach** [comment]
Yup, that's the plan!

**Review by ccordoba12 — APPROVED** [review]
3.3.1 is up.

**Comment by CAM-Gerlach** [comment]
Noice! Thanks @ccordoba12

**Comment by ccordoba12** [comment]
I'll wait to see how it looks in develop before merging with production.

**Comment by CAM-Gerlach** [comment]
Yep, I'm checking too...just reloading the page waiting for the build to finish.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Looks good to me on a quick run through, unless you want to change the date to today (the 14th) instead of yesterday (the 13th), the same date the previous post was published (would be nice to separate them at least a little).

**Comment by ccordoba12** [comment]
Ok, I'll do it right away. But what if we also shorten the title to be only

> Spyder 3.3.0 and 3.3.1 released!

? What do you say?

**Comment by ccordoba12** [comment]
Love the screenshots, by the way! Very nice job there!

**Comment by CAM-Gerlach** [comment]
Okay, sure. I gotta run so no time to argue :)

**Pull request merged**
