### PR TITLE
Update banner margins and scale to avoid it being too large on site

### PR DESCRIPTION
**Pull request by CAM-Gerlach**
As it seems the site is scaling the banner image by the smallest rather than the largest dimension, my #81 screwed things up and its now way too large. This should fix it once and for all...I hope. :crossed_fingers:

### CODE REVIEW

**Review by ccordoba12 — APPROVED** [review]

**Comment by ccordoba12** [comment]
@CAM-Gerlach, this morning image had the right borders. Please remove the empty border at the bottom you added to this one and add it to the top instead.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 As @jnsebgosselin stated there and I confirmed on two different machines, two different monitors and three different browsers, half or more of the plots are cut off and unable to be seen even with scrolling on a standard 16:9 monitor, and that's with each browser configured for minimal extra chrome (no tab bar, bookmarks bar, status bar, toolbars, etc). It could use a little extra margin at the top to avoid the logo getting cut off on some browsers (ironically enough it wasn't cut off on IE and was on FF and Chromium), but we can't really spare any at the bottom since even with the standard minimal UI, we're right at the limit:

image

Are you on 16:10 or something (as my main monitors are, which is why it looked perfect to me too this morning)? Can you send a screenshot of how it looks for you, and on what browser (I'm on FF, though I also tested on Chromium and IE).

**Comment by ccordoba12** [comment]
This is how it looks in mine

seleccion_002

As you can see, there's too little space on the top and too much at the bottom. So please try to add at least a bit more space at the top and make the screenshot run to the bottom. And if plots are not seen, then reduce the height of the variable explorer and make them appear higher.

I'm almost sure the theme we're using was designed for the banner image to run to the bottom.

**Comment by ccordoba12** [comment]
I also verified that it looks like this in other monitors, not just mine.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 

> This is how it looks in mine

Right, that's exactly how it looks on my 16:10 monitor as well, although with the tight cropping of the screenshot and the lack of any accompanying information about that monitor or any of the others you've tested it on, I can't confirm your resolution or aspect ratio for comparison. However, 16:9 is the most common aspect ratio worldwide by a large margin, and will only get more so as few to no monitors of other (or at least narrower) aspect ratios have been manufactured in quantity for many years, and as mentioned the above screenshot is representative of where the bottom margin falls on 16:9 across multiple resolutions, machines, and browser rendering engines. If we're going to optimize for anything, it should be 16:9.

> As you can see, there's too little space on the top

Yes indeed, that needs to be fixed regardless.

> too much at the bottom

Far better to have a little extra white space there then abruptly cutting off the whole bottom of the window and much of the content. The real problem with the appearance isn't really the bottom margin by itself, but the lack thereof on the top leading to it looking unbalanced and skewed, which doesn't look too good especially on 16:10.

> So please try to add at least a bit more space at the top

Will do.

> make the screenshot run to the bottom.

> I'm almost sure the theme we're using was designed for the banner image to run to the bottom.

The original theme is designed for the image to fill the entire frame, that's in fact why it it is set to enlarge to fill the frame (scaling on the smallest dimension) vs. fitting the entire image in the frame (scaling on the largest dimension). This isn't at all how we're using it; to display a graphical banner and a content-motivated screenshot over part of the area below.

Specifically,the [original image](https://github.com/SteveLane/hugo-icon) covers the whole frame, borderless, while the screenshot only occupies a moderate portion and has margins around the other three sides. Generally speaking, this is a design no-no without a very good reason and indeed doesn't look good at all in this one.

Further, the original image was a simple, gradual/continuous background, with no clearly defined borders; it doesn't matter hugely to the look exactly where it is cut off (this would work nearly as well with a photographic image with the subject near the center of the frame and nothing too important, or at least relatively continuous tones, near the edges). On the other hand, our screenshot most certainly does have clearly defined natural boundaries, and looks significantly off if cropped off before them (the edge of the window).

The fundamental problem is that the image is being fit to the screen on the width dimension, when what in fact matters is the height. Therefore, ideally it should just be set to "fit" (long dimension) scaling rather than "fill" (short dimension). However, if that's not easily done with the current theme, we can effectively force it to and bypass all this nonsense by just adding more margin to the sides (since we've got plenty of room to scale up there) as to force the image to "fit" to the height dimension instead. Then, it should scale to be the same height on all monitors, while letting the width float.

It also could do with being a little larger in relative size, which would need to be done with a new screenshot with a little shorter window height (too much would look odd, but I can probably get away with another 100-150 px or so).

Finally, while (as I explain above) it still needs some margin on the bottom, it could certainly do with less than it has on our 16:10 screens. Therefore, once we can control its height precisely with the above so it scales to the proper place on all monitors, we can cut the margin much closer without worrying it will get cut off on some screens and be too larger on others.

Even better would be just to just set the image scaling to "fit" (fit to long edge) rather than "fill" (fit to short edge), as that would avoid having to crank the width wider (a bit of a kludge) and could lead to it scaling too big on vertical/portrait mode monitors, but not sure how easy it is to do with our theme.

I'll push the changes stated above tomorrow morning, and you can see what you think. Thanks for your patience throughout this ordeal,

**Comment by CAM-Gerlach** [comment]
We also got feedback from @goanpeca on Gitter that he'd prefer a more science-oriented file be shown vs. Spyder's mainwindow. My rationale for the latter was, aside from the coolness factor of being the very code that was generating the window used to display it, it showcased that Spyder was written in the same language it was designed to be used for, and conversely could display and edit the very code that was running Spyder itself. However, I certainly can see a good argument for showing more typical scientific code instead, and this was a potential concern I expressed as well on #75 and asked for feedback on that point. 

If the consensus is that I should redo it with some more scientific code, and preferably someone can provide some for me (most of my "real" data analysis and ML related code is a trade secret of my current employer, much to my strong displeasure and they wouldn't be too happy with my plastering it over the Spyder homepage, and most of my personal stuff is either not fit for public consumption or in R) then I can use that instead in the screenshot tomorrow.

**Comment by ccordoba12** [comment]
> Right, that's exactly how it looks on my 16:10 monitor as well, although with the tight cropping of the screenshot and the lack of any accompanying information about that monitor or any of the others you've tested it on, I can't confirm your resolution or aspect ratio for comparison.

The resolution of my screenshot is 1680x1050, but it looks the same in 1440x900 and 1366x768. By the way, 1366x768 is still the most common resolution according to [Firefox metrics](https://hardware.metrics.mozilla.com/), followed by 1920x1080.

I don't know if that corresponds to 16:10 or 16:9, sorry.

> Finally, while (as I explain above) it still needs some margin on the bottom, it could certainly do with less than it has on our 16:10 screens.

Ok, good. Then please try to add more margin to the top and reduce it at the bottom. That should fix the screenshot.

> We also got feedback from @goanpeca on Gitter that he'd prefer a more science-oriented file be shown vs. Spyder's mainwindow

I agree with him on that point. Please use some scientific code there. It could be the code you used to generate the Matplotlib plots that are shown in the console, as simple as that.

Also, please don't use the Pep8 option to generate the screenshot because it generates too much warnings.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 

> The resolution of my screenshot is 1680x1050, but it looks the same in 1440x900 and 1366x768. By the way, 1366x768 is still the most common resolution according to Firefox metrics, followed by 1920x1080.

> I don't know if that corresponds to 16:10 or 16:9, sorry.

Thanks, that's indeed what I needed. So your monitor is indeed 16:10, as is 1440 x 900, and 768p and 1080p are both 16:9. (You just divide the big number by the little number :) )

> Ok, good. Then please try to add more margin to the top and reduce it at the bottom. That should fix the screenshot.

Will do, and will also widen the margins as I suggested to make it display the same on all monitors, regardless of resolution or aspect ratio, and make the window a little shorter, as you suggested previously, to allow it to be a little larger and easier to view on smaller screens. I'll need to do that when I get home later, since my monitors and test box are there.

> I agree with him on that point. Please use some scientific code there.

Excellent; agreed, I'd been thinking the same.

> It could be the code you used to generate the Matplotlib plots that are shown in the console, as simple as that.

Its all really ugly and hacked together; its just my scratch/temp file where I dump all my code for testing. I didn't want to look unprofessional or self-serving. But I can give it a shot and see how it looks.

> Also, please don't use the Pep8 option to generate the screenshot because it generates too much warnings.

Oh. okay; I included it to demonstrate that functionality. What about if I ensure there are no warnings on the page of code that's shown so it looks clean, but a few can be seen in the right sidebar to demonstrate that? I can also scatter a few #TODO comments to demonstrate Spyder's annotation capabilities in the right and left sidebars without it looking like distracting errors/warnings.

**Comment by ccordoba12** [comment]
> Its all really ugly and hacked together

Please use this code instead:

https://gist.github.com/ccordoba12/16740156420fb678bb5ba67c3ee3aae4

> What about if I ensure there are no warnings on the page of code that's shown so it looks clean, but a few can be seen in the right sidebar to demonstrate that?

Ok, that's better.

> I can also scatter a few #TODO comments to demonstrate Spyder's annotation capabilities

That would be nice too.

**Comment by CAM-Gerlach** [comment]
> Please use this code instead:

Perfect, thanks! Just what I was looking for...

> Ok, that's better.

Will do.

> That would be nice too.

Ditto.

I'll push it shortly once I get home along with one for the readme.

**Pull request merged**
