### PR TITLE
PR: Update logo across website

### PR DESCRIPTION
**Pull request by isabela-pf**
This PR replaces logo images files used in the website. Please let me know if anything looks wrong.

I did not replace `assets/static/images/mainpage_screenshot.png` because I wasn't sure if that was automatically generated.

---
Logo changes across the project and voting can be tracked on [spyder #13181](https://github.com/spyder-ide/spyder/issues/13181) and [ux-improvements #50](https://github.com/spyder-ide/ux-improvements/issues/50).

### CODE REVIEW

**Comment by ccordoba12** [comment]
Closing and reopening to see if Netlify kicks off.

**Comment by isabela-pf** [comment]
Other feedback 
 - [x] Update all logos and banners with logo fix

**Review by ccordoba12 — APPROVED** [review]
Thanks a lot for your help with this @isabela-pf!

**Comment by CAM-Gerlach** [comment]
Thanks for doing this @isabela-pf , everything looks very good! It looks like optipng wasn't run on any of the images, which reduced their sizes by an average of around 2x for free. I submitted PR #201 to fix this issue, though they will still persist indefinitely in the repo itself; nothing we can really do about that without rewriting history.

However, there is a more significant problem: The size of the hero image has increased by 1000% (!), to a whopping 4.5+ MB. This is a very big hit for users, especially newer ones loading the site for the first time or that don't have access to good internet. Given the that both the image itself and the screenshot and logotype within are the same size and similar in content, and optipng barely made any difference (<3 % reduction), I strongly suspect the primary cause is the screenshot being rescaled by a non-integer multiple, one if not multiple times before appearing in the final rendered PNG. This results in very poor compression efficiency, as well as slightly inferior crispness and quality.

In order to fix this, @isabela-pf , can you (or @juanis2112 , if she took the original screenshot) ensure the screenshot is at a 1:1 ratio (100% size) to the original source, by sizing the Spyder window and display rendered resolution accordingly? For reference, the original I made was approximately 1770 x 780 ; it doesn't have to be exactly those dimensions but it should be close enough that it can be added to the final layout at exactly 1:1 size. If for some reason that isn't possible, at the very least it should be a 2:1 ratio with nearest neighbor downsampling, though encoding performance and (to a lesser extent) quality will suffer somewhat.

Let me know if I can be of further assistance. Thanks!

**Comment by isabela-pf** [comment]
I can look into this, though I may not be able to fix it right away. 

Thanks for letting us know, @CAM-Gerlach! Good to see you around!

**Comment by CAM-Gerlach** [comment]
Thanks @isabela-pf ! Good to see you too! I'll open an issue to discuss and track this further.

**Pull request merged**
