### PR TITLE
PR: Add precommit hooks to automatically check for and fix errors, regressions and style/lint issues

### LINKED ISSUE #183: Minor followup changes after implementation of new theme
* [x] Change FG color to theme default
* [x] Don't use different feature background on hover
* [x] Eliminate Spyder Reports from plugins
* [x] Fix order of donate and sponsors and nix sponsors from navbar to make it shorter
* [x] Add links to components and sponsors
* [x] ~~Reduce size of Spyder screenshot to avoid it cropping~~ Looks much too small on desktop, much more so than expected; recommend discussing this in a separate issue and addressing this in another PR by adding an abstract background (e.g. zoomed and blurred Spyder) and either reducing size as originally planned, switching to "cover" mode, and/or making the half-height breakpoint occur earlier
* [x] Change logo to raster and eliminate Blog
* [x] Copyedit mainpage text
* [x] Update screenshot in README

### PR DESCRIPTION
**Pull request by CAM-Gerlach**
As originally discussed on spyder-ide/website-spyder#177 . There is a corresponding PR on the theme repo that implements them theme-side, that this PR incorporates (and the commit pointing the theme to that branch will need to be dropped, and it rebased accordingly, before this is merged), spyder-ide/lektor-icon#13 . This work can also be applied with minimal changes to perform the same automatic services for the docs and docs theme repo, if desired. A PR to fix #183 will follow immediately after this is merged.

I'm adding some automated [pre-commit](https://github.com/pre-commit/pre-commit) checks for common issues, to warn for (and in most if not almost all cases of things that aren't straight-up errors, automatically fix) regressions as well as easy to introduce and hard to catch errors, like broken links, forgotten merge conflicts, and HTML/CSS/config file errors, as well as handle a variety of menial tasks automatically like optimizing PNGs and fixing whitespace, EoL, style issues and more, so you shouldn't ever have to worry about those sorts of things again, it will all be taken care of automagically when you commit.

They'll be able to run on both our CIs when you push and locally when you commit. For the latter, you can simply install the `pre-commit` package with pip or conda, type `pre-commit install`, and it'll take care of the rest (it'll install and configure everything it needs, even binary executables and other packages for languages, in an isolated environment with zero intervention, on all common platforms; the initial install could take a few minutes but after that it should only take a few seconds per commit). Step by step instructions are included in the README and contributing guide.

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
@ccordoba12 @dalthviz @juanis2112 This is ready for final review, pending merge of the corresponding theme PR. It makes no changes to the site itself, just the infra, so review should mainly consist of testing the pre-commit hooks on each of your three major platforms.

To do so, please run the following commands in the root of this branch to comprehensively verify that the pre-commit checks install and run smoothly on each of your three platforms (you won't normally need to do all of this, its just for testing). Thanks.

~~@dalthviz You probably already do, but assuming you're testing this on Windows, make sure you have Developer mode enabled so that [symlinks work](https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/), or else run at least the third command from an admin command prompt (only needs to be done once); one of the packages requires them for some reason (which probably can be fixed) and they are also an integral part of this repo already (the example site doesn't work without them).~~ Fixed by pinning node to 14.x for now, hopefully this can be addressed upstream.

```bash
conda install -c conda-forge pre-commit
pre-commit install
pre-commit install --hook-type commit-msg
pre-commit install-hooks
pre-commit run --all-files
git commit --allow-empty -m "Test that commit message hook works properly"
```

Once this is merged, we can merge the corresponding website PR. Thanks.

**Comment by dalthviz** [comment]
Hi @CAM-Gerlach after a quick overview of the changes, maybe an `exclude` config for the `git submodule` of the repo theme path should be added? Or maybe at least the same things being excluded in the `pre-commit` config of the theme repo should be excluded here too?

**Comment by CAM-Gerlach** [comment]
Good question @dalthviz  . Actually, pre-commit uses Git's index to detect and filter the files to add, which doesn't include submodule files (since those are handled by the theme's own pre-commit config). so there's no need to do so manually, but good thinking to check.

**Comment by ccordoba12** [comment]
> To do so, please run the following commands in the root of this branch to comprehensively verify that the pre-commit checks install and run smoothly on each of your three platforms (you won't normally need to do all of this, its just for testing). Thanks.

I got this error (the rest ran smoothly):

```python-traceback
Check for added large files..............................................Failed
- hook id: check-added-large-files
- exit code: 1

Traceback (most recent call last):
  File "/home/carlos/.cache/pre-commit/repoq6i73dk3/py_env-python3.7/bin/check-added-large-files", line 8, in <module>
    sys.exit(main())
  File "/home/carlos/.cache/pre-commit/repoq6i73dk3/py_env-python3.7/lib/python3.7/site-packages/pre_commit_hooks/check_added_large_files.py", line 65, in main
    enforce_all=args.enforce_all,
  File "/home/carlos/.cache/pre-commit/repoq6i73dk3/py_env-python3.7/lib/python3.7/site-packages/pre_commit_hooks/check_added_large_files.py", line 33, in find_large_added_files
    filenames_filtered = set(filenames) - lfs_files()
  File "/home/carlos/.cache/pre-commit/repoq6i73dk3/py_env-python3.7/lib/python3.7/site-packages/pre_commit_hooks/check_added_large_files.py", line 21, in lfs_files
    return set(json.loads(lfs_ret)['files'])
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/carlos/.cache/pre-commit/repoq6i73dk3/py_env-python3.7/bin/check-added-large-files", line 8, in <module>
    sys.exit(main())
  File "/home/carlos/.cache/pre-commit/repoq6i73dk3/py_env-python3.7/lib/python3.7/site-packages/pre_commit_hooks/check_added_large_files.py", line 65, in main
    enforce_all=args.enforce_all,
  File "/home/carlos/.cache/pre-commit/repoq6i73dk3/py_env-python3.7/lib/python3.7/site-packages/pre_commit_hooks/check_added_large_files.py", line 33, in find_large_added_files
    filenames_filtered = set(filenames) - lfs_files()
  File "/home/carlos/.cache/pre-commit/repoq6i73dk3/py_env-python3.7/lib/python3.7/site-packages/pre_commit_hooks/check_added_large_files.py", line 21, in lfs_files
    return set(json.loads(lfs_ret)['files'])
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/carlos/.cache/pre-commit/repoq6i73dk3/py_env-python3.7/bin/check-added-large-files", line 8, in <module>
    sys.exit(main())
  File "/home/carlos/.cache/pre-commit/repoq6i73dk3/py_env-python3.7/lib/python3.7/site-packages/pre_commit_hooks/check_added_large_files.py", line 65, in main
    enforce_all=args.enforce_all,
  File "/home/carlos/.cache/pre-commit/repoq6i73dk3/py_env-python3.7/lib/python3.7/site-packages/pre_commit_hooks/check_added_large_files.py", line 33, in find_large_added_files
    filenames_filtered = set(filenames) - lfs_files()
  File "/home/carlos/.cache/pre-commit/repoq6i73dk3/py_env-python3.7/lib/python3.7/site-packages/pre_commit_hooks/check_added_large_files.py", line 21, in lfs_files
    return set(json.loads(lfs_ret)['files'])
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/carlos/.cache/pre-commit/repoq6i73dk3/py_env-python3.7/bin/check-added-large-files", line 8, in <module>
    sys.exit(main())
  File "/home/carlos/.cache/pre-commit/repoq6i73dk3/py_env-python3.7/lib/python3.7/site-packages/pre_commit_hooks/check_added_large_files.py", line 65, in main
    enforce_all=args.enforce_all,
  File "/home/carlos/.cache/pre-commit/repoq6i73dk3/py_env-python3.7/lib/python3.7/site-packages/pre_commit_hooks/check_added_large_files.py", line 33, in find_large_added_files
    filenames_filtered = set(filenames) - lfs_files()
  File "/home/carlos/.cache/pre-commit/repoq6i73dk3/py_env-python3.7/lib/python3.7/site-packages/pre_commit_hooks/check_added_large_files.py", line 21, in lfs_files
    return set(json.loads(lfs_ret)['files'])
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Does this require git-lfs installed?

**Comment by CAM-Gerlach** [comment]
I think you might be on the right track. The hook is not supposed to require Git-LFS though it uses it when available, and taking a look at the hook's source code (its a first-party hook, so surprised this hasn't come up before) it does have handling for when `git lfs` isn't available, out of date, etc., but it doesn't seem to cover your case. It appears what might have happened is for some reason `git lfs status --json` returns zero but `stdout` is null/empty, so `json.loads` borks. I do happen to have `gif lfs` installed myself (though I haven't really configured nor used it), and I cannot repro the problem. 

Ideally it should be fixed to handle your case correctly (i,e. checking for and handling null `stdout`), as it can be useful in detecting when overly large image files are committed to the site, but for now we can just disable it. Its also one of the slowest hooks for what it does (taking up to a few seconds to run ), so it will also speed things up a little too.

**Comment by ccordoba12** [comment]
Ok, thanks for taking a look at that. I also found I had a very old (four years) version of `git-lfs` installed, which was the culprit of the error. Once I installed the latest one, the error was gone.

**Comment by CAM-Gerlach** [comment]
Thanks, I dropped the commit disabling that check.

**Review by ccordoba12 — APPROVED** [review]
Thanks @CAM-Gerlach!

**Comment by CAM-Gerlach** [comment]
Pinned Markdownlint to Node 14 to avoid a potential symlink issue installing one of the hooks on Windows in some configurations with npm 7.x (described in pre-commit/pre-commit#1681 ) until its hopefully resolved in npm and/or markdownlint-cli upstream.

**Comment by dalthviz** [comment]
@CAM-Gerlach when running the command to install pre-commit I get the following:

```
(pre-comm) C:\Users\Daniel\Documents\Spyder\website\CAM\website-spyder>pre-commit install-hooks
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\Daniel\\Anaconda3\\envs\\pre-comm\\python.exe', '-mvirtualenv', 'C:\\Users\\Daniel\\.cache\\pre-commit\\repoon5paske\\py_env-python3.7')
return code: 1
expected return code: 0
stdout:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Daniel\\Anaconda3\\envs\\pre-comm\\Lib\\venv\\scripts\\nt\\python.exe'

stderr: (none)
Check the log at C:\Users\Daniel\.cache\pre-commit\pre-commit.log
```

What else is needed for the installation?

**Comment by CAM-Gerlach** [comment]
Actually, this is way bigger than just pre-commit, virtualenv > 2.0.33 is broken on conda and Windows + Python 3.7+, see pre-commit/pre-commit#1675  and pypa/virtualenv#1986 for more info. `conda install -c conda-forge virtualenv=20.0.33` should fix it, and I'll re-add a `requirements.txt` file that includes it and simply the installation instructions accordingly (I removed it since it messed with Netlify, and there was only 1 dependency spec (Lektor) then, but I'll get it working again).

**Comment by CAM-Gerlach** [comment]
Done, also expanded the installation and setup instructions with more helpful information, particularly about pre-commit and synced them between the theme and the site.

**Comment by dalthviz** [comment]
Just in case @CAM-Gerlach after running `pre-commit run --all-files` I got this:

```
Check for useless excludes...............................................Passed
Trim Trailing Whitespace.................................................Passed
Normalize mixed line endings.............................................Passed
Fix End of Files.........................................................Passed
Remove Unicode BOM.......................................................Passed
Replace tabs with spaces.................................................Passed
Check spelling...........................................................Passed
Fix spelling.............................................................Passed
Beautify Bash scripts....................................................Passed
Lint Bash scripts........................................................Failed
- hook id: bashate
- exit code: 1

bashate: [WinError 2] El sistema no puede encontrar el archivo especificado

Lint and fix CSS (stylelint).............................................Passed
Check CSS (CSSlint)......................................................Passed
Format INI...............................................................Passed
Lint and fix JavaScript..............................(no files to check)Skipped
Lint Jinja templates.................................(no files to check)Skipped
Check JSON...............................................................Passed
Generate Markdown ToCs...................................................Passed
Lint Markdown............................................................Passed
Check Toml...............................................................Passed
Check Xml................................................................Passed
Format Yaml..............................................................Passed
Check Yaml...............................................................Passed
Lint Yaml................................................................Passed
Replace CRLFs with LF....................................................Passed
Check for Unicode replacement chars......................................Passed
Check for added large files..............................................Passed
Check for case conflicts.................................................Passed
Check that executables have shebangs.....................................Passed
Check for merge conflicts................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Prevent commits to wrong branch..........................................Passed
```

And after running `git commit --allow-empty -m "Test that commit message hook works properly"`:

```
Check for useless excludes...........................(no files to check)Skipped
Trim Trailing Whitespace.............................(no files to check)Skipped
Normalize mixed line endings.........................(no files to check)Skipped
Fix End of Files.....................................(no files to check)Skipped
Remove Unicode BOM...................................(no files to check)Skipped
Replace tabs with spaces.............................(no files to check)Skipped
Check spelling.......................................(no files to check)Skipped
Fix spelling.........................................(no files to check)Skipped
Beautify Bash scripts................................(no files to check)Skipped
Lint Bash scripts....................................(no files to check)Skipped
Lint and fix CSS (stylelint).........................(no files to check)Skipped
Check CSS (CSSlint)..................................(no files to check)Skipped
Format INI...........................................(no files to check)Skipped
Lint and fix JavaScript..............................(no files to check)Skipped
Lint Jinja templates.................................(no files to check)Skipped
Check JSON...........................................(no files to check)Skipped
Generate Markdown ToCs...............................(no files to check)Skipped
Lint Markdown........................................(no files to check)Skipped
Check Toml...........................................(no files to check)Skipped
Check Xml............................................(no files to check)Skipped
Format Yaml..........................................(no files to check)Skipped
Check Yaml...........................................(no files to check)Skipped
Lint Yaml............................................(no files to check)Skipped
Replace CRLFs with LF................................(no files to check)Skipped
Check for Unicode replacement chars..................(no files to check)Skipped
Check for added large files..........................(no files to check)Skipped
Check for case conflicts.............................(no files to check)Skipped
Check that executables have shebangs.................(no files to check)Skipped
Check for merge conflicts............................(no files to check)Skipped
Check for broken symlinks............................(no files to check)Skipped
Prevent commits to wrong branch..........................................Passed
Check commit message.....................................................Passed
Check commit message spelling............................................Passed
[add-precommit-hooks fd7adb8] Test that commit message hook works properly
```

If that is the expected behavior LGTM :+1:

**Comment by CAM-Gerlach** [comment]
@dalthviz That all looks good except for the `bashate` failure. Looks like bashate only works from Git bash or another bash-like interpreter; I was able to repro the error when running it from cmd. Running git this way instead of through git bash is deprecated, but I don't want to completely exclude such users, so I can set that check to manual and only run it on the CI.

**Comment by CAM-Gerlach** [comment]
@dalthviz @juanis2112 Pushed the changes to address both of your issues; I confirmed `bashate` does not run and the fix to the Python interpreter version does solve the problem, so this should be good to approve. Thanks for all your invaluable patience and assistance.

Once you do and tests pass here and on spyder-ide/lektor-icon#13 , I'll merge that, drop the commit pointing to that branch, and finally merge this, and then I can coordinate with @juanis2112 to rebase spyder-ide/website-spyder#185 accordingly.

**Review by juanis2112 — APPROVED** [review]
Looks good to me. Thanks @CAM-Gerlach

**Comment by CAM-Gerlach** [comment]
Thanks for all your help testing @ccordoba12 @dalthviz and @juanis2112 , I think we're ready to go. I merged spyder-ide/lektor-icon#13 and dropped the commit pointing this to my branch, and @dalthviz I confirmed on my machine that `bashate` is properly set to manual only and I can no longer reproduce the error running on `cmd`, so I think you should be good to approve and we can merge once Travis gets its act together.

**Review by dalthviz — APPROVED** [review]
Thanks @CAM-Gerlach LGTM :+1:

**Pull request merged**
