### PR TITLE
PR: Match the blog style with the new intro page

### LINKED ISSUE #73: Change style of the blog page
Following a style similar to http://blog.rstudio.com/

### PR DESCRIPTION
**Pull request by dalthviz**
Fixes #73

### CODE REVIEW

**Comment by dalthviz** [comment]
@ccordoba12 a preview:

prev

**Comment by dalthviz** [comment]
@ccordoba12 a preview:

imagen

imagen

imagen

imagen

**Comment by ccordoba12** [comment]
It's looking really good @dalthviz! My comments:

1. I like the changes to the navbar, but please remember that we need to use the same banner used in the main page. What you could do is to remove the words *The Scientific Python development environment*, and simply leave the logo and *Spyder* next to it. But we need to use the same logo and font from the main page :-)
2. Please change the background color of the blog from gray to white and add a shadow to the navbar to distinguish it from the background.
3. The author's photo and the blog's title are misaligned, both in the main blog page as well as in the page for each blog. Look at how it's done in the [Jupyter blog](https://blog.jupyter.org/): the photo is on top and the blog's header is below it.
4. Code snippets should be highlighted. I don't know if that's something Lektor can do or not. If not, we should try to implement it in a different PR.

**Comment by ccordoba12** [comment]
@dalthviz, could you post a screenshot with your latest changes?

**Comment by dalthviz** [comment]
@ccordoba12 a preview:

imagen

imagen

imagen

---------------------------
The navbar logo

imagen

imagen

**Comment by ccordoba12** [comment]
Thanks @dalthviz! This is looking better and better with each iteration! About the post headers, a couple of comments:

1. Make the author's photo smaller, to be of the same size as the author's name and date next to it.
2. Align the author's photo, name and date to the left.
3. Align the blog title to the left too.

**Comment by dalthviz** [comment]
@ccordoba12 like this?:
### Option 1
imagen

Or 

### Option 2
imagen

**Comment by ccordoba12** [comment]
Thanks for the quick response! Option 2 is what I'd like to see, but with the name and date closer to the photo. Also, please make the date to have a smaller font than the name (1pt smaller should be enough).

**Review by ccordoba12 — APPROVED** [review]
Let's see how this looks to give you more feedback ;-)

**Pull request merged**
