### PR TITLE
PR: Fix minor issues in the home page

### LINKED ISSUE #68: A couple of more issues with the new theme
The new home page is looking really good! This is my second round of minor issues before considering it's done:

1. We need to change the current favicon because it's using the icon from the old site in Firefox and the Hugo icon theme in Chrome.
2. Navbar sections are not changing when moving from one section to another. For example, *Componets* is not selected after entering that section.
3. I don't like that the banner is expanded to the full window width. We should set a maximum width (perhaps 700px, I don't know).
4. We should only display the working links that appear below each member of the *Team*. I mean, for example if someone doesn't have an Instagram account (me) that link and icon shouldn't be displayed.
5. The *Plugins* section background should be light gray (as the *Overview* one), the *Team* background should be white and the footer one should be light gray. That way we will be alternating between those two colors in the whole page.

### PR DESCRIPTION
**Pull request by dalthviz**
Fixes #68

### TODO:

- [x] Change favicon (possible need to delete cache to refresh favicon.ico)
- [x] Fix sticky navbar.
- [x] Width of the banner.
- [x] Working links in `Team` section.
- [x] Background colors of the sections.

### CODE REVIEW

**Comment by goanpeca** [comment]
@ccordoba12 @dalthviz should I point spyder-ide.org to the actual site?

**Comment by dalthviz** [comment]
@goanpeca I thought that we are going to do that after changing the style of the blog, althought I'm will have done that the next week probably :). So in a week or so maybe we should do the redirection of the domain?

**Comment by goanpeca** [comment]
@dalthviz ok, ping me then ;-)

**Comment by dalthviz** [comment]
@ccordoba12 a preview of the banner:

imagen

**Comment by ccordoba12** [comment]
@dalthviz, I like it, it looks good. For the banner, please take the left part of image **2b** (without the border) from 

https://github.com/spyder-ide/spyder/pull/6352#issuecomment-368077600

**Comment by ccordoba12** [comment]
Also, the width of the banner must be the same of the text below it.

**Review by ccordoba12 — APPROVED** [review]
Thanks a lot @dalthviz! Let's merge this one, so I can give you feedback over the live website.

**Pull request merged**
