### PR TITLE
PR: Make banner higher res, align, and add more compelling screenshot

### LINKED ISSUE #71: Use a high resolution image of Spyder in the banner
I'll work on this one.

### PR DESCRIPTION
**Pull request by CAM-Gerlach**
Fixes #71 .

The banner was rendered at a much higher resolution out of the original SVG, with some minor fixes to alignment internally and between it and the screenshot.

The screenshot was taken from a full 1200p monitor, and with (hopefully) a much more compelling layout including multiple editor panes, the project explorer, a wide variety of different types in the variable explorer, a compelling plot and some code in the console, multiple console and panel tabs open, a much more attractive and visible color scheme better displaying Spyder's syntax highlighting, auto-highlighting, and color theme capabilities (I tried the default light theme but it looked really bad at that size, especially on a wide background...if you really want, though I can show you a version with that), all rendered with UI elements much smaller leading to much less chrome and more content, and looking much more modern in that regard like its peers.

Unfortunately, I followed the instructions in the readme to install and run lektor, but for some reason it only displayed a version of the site with the old, out of date theme, and with some elements not even working, so I wasn't able to directly preview it—if someone could or provide guidance, that would be very helpful.

In any case, this is what the image itself looks like:

image

And as a bonus, its pretty cool that it is displaying Spyder's own code, specifically that used to create and test the very MainWindow being shown.

### CODE REVIEW

**Comment by ccordoba12** [comment]
This looks good, thanks @CAM-Gerlach! My suggestions:

* Please leave more space between the banner and the screenshot. I think they are too close right now.
* The screenshot needs to go to the bottom, i.e. you don't need to leave a white border below it. That's because our current theme tries to scale the image to include that border and so things look bad. You can also cut the screenshot not exactly at the bottom of the screen, but somewhere above it too.
* Although it's cool to show a lot of the cool things Spyder has to offer in the screenshot, I think it should show instead Spyder with its default pane distribution and color scheme. Of course, this is open to debate, but I think that's important so that people can identify the software they installed with what they are seeing in our webpage.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 

> Please leave more space between the banner and the screenshot. I think they are too close right now.

Agreed; was thinking the same upon reflection.

> The screenshot needs to go to the bottom, i.e. you don't need to leave a white border below it. That's because our current theme tries to scale the image to include that border and so things look bad.

Okay; I was just trying to replicate the current layout as a starting point. Will do.

> You can also cut the screenshot not exactly at the bottom of the screen, but somewhere above it too.

Good idea; I'll see how it looks.

> Although it's cool to show a lot of the cool things Spyder has to offer in the screenshot, I think it should show instead Spyder with its default pane distribution and color scheme

Personally, I'd have to strongly disagree with that reasoning, with the following rationale. If we still aren't in agreement, then maybe we can get others to weight in.

If it was showing third party spyder plugins, or features from Spyder 4 that aren't in stable yet, then yes that certainly could be misleading or confusing to users, but saying we have to show Spyder in a pristine, absolutely clean default configuration without even built-in features that take a few seconds to enable is a step too far for this particular application, IMO. The explicit purpose of the image is to make a strong, positive first impression on people discovering Spyder for the first time, and demonstrate visually in one image what Spyder is capable of; it would make sense to start from the defaults in a tutorial or the documentation (and perhaps even for the Readme?), but certainly not what effectively is our main avenue of promoting our software.

Thing about it this way—if you were to put up a billboard or a post getting the word out about Spyder, would you want to use the bland defaults and not demonstrate many of its built in features, or make it look as good as it can and really show off what it can do? Suppose you had a job interview or a first date—would you want to wear exactly what you were wearing when you first met the person or sent them a photo, or would you dress up/down for the occasion and make sure you looked your best, tailored to your audience? 

Furthermore, look at Rstudio—on their [homepage](https://www.rstudio.com/), the closest thing they have to a screenshot is a highly stylized cartoon of the interface that looks far more different from "real life" than the above. Furthermore, on the [main Rstudio software page](https://www.rstudio.com/products/RStudio/) their only screenshot shows Rstudio with the dark theme applied—not just to text as here, but to the entire UI—and a number of non-default UI changes (terminal instead of console, data frame viewer instead of editor, different tabs open, editor panel open at all—console only is actually the default, etc). Or look at JupyterLab—every page of their [site](https://blog.jupyter.org/jupyterlab-is-ready-for-users-5a6f039b8906) and [documentation ](https://jupyterlab.readthedocs.io/en/stable/)shows a totally different layout, content and panes open—and I'm not sure any of them are the default.

Again, we have to keep in mind the purpose of that image—it isn't to identify exactly how the program will look upon opening it for the first time, but rather show off what it can do. As a matter of fact, creating the plot, running console code, opening editor files, and loading the Variable Explorer items took much more user work to generate than the simple UI changes (adding a split pane and picking a different color scheme, along with opening a few other panel and console tabs in the background), and I'd argue make at least an equal, if not a greater impact on how different the interface looks from the default; however, almost all those former elements are present in both the current screenshot and the one from our readme (in fact, every one is present between the two of them), and I don't imagine getting rid of those is suggested as well. Furthermore, the previous version has a much more radically different pane layout than this one vs. the default, as it has the console to the bottom left of the editor, the editor half-height, and the file explorer bottom right. That's a much bigger change IMO than just splitting the editor pane and leaving everything else as default (besides some extra background tabs open in the default locations).

Finally, *even if* users were to take the first image they see on the website as authoritatively what they should see when opening Spyder to "identify the software" (minus the aforementioned content), it would look very similar, I'd certainly argue more so than the heavily outdated Readme screenshot or the much differently laid out previous website screenshot, and I can't imagine it being much of any trouble for even a minimally informed user to tell they are the same program, considering most IDEs and even text editors out there have multiple editor panes and syntax highlighting themes in common use, and otherwise the UI is essentially identical. (And, *even if* it was to confuse/turn off a significant number of users, we have to balance that with the additional users showing Spyder's full capabilities would attract, likely those doing more meaningful things with it anyway) Compare:

Proposed:
image

Default:
image

Previous Website:
image

Readme:
image

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Pushed a new commit with the changes above. Note that I only cut the bottom margin, as that was the only one you mentioned, but I can eliminate the others as well if you need. Again, I just can't see the actual final site layout locally due to the aforementioned strange issues with ``lektor``

image

**Comment by jnsebgosselin** [comment]
Good job @CAM-Gerlach. I won't have time to actively participate in this for the next few days, so I removed myself from the "official " review request so I don't block any progress on this. I've read your answer to Carlos quickly in diagonal (because I do not have much time and there was so much text), but I'll give you some feedback now :

My vote goes to default too, but with a slightly larger `project explorer` panel and a reduced width of the main window so there is less horiz. white space in the `editor`. Also is this Windows 8 or 10? I think that would be better if it was done in 10.

Finally the fact that we see  `C:/Users/C. A. M. Gerlach/Documents/dev/SpyderDev` in the title bar of the main window, in the working dir. editbox and in the editor plugin title bar doesn't look professional. Something more impersonal would look better imo. Something like :

image

**Comment by jnsebgosselin** [comment]
Just to clarify the purpose of the screenshot above. I posted it to show an example of a more impersonal `path` that could be used, not as an example of how the screenshot should look like.

**Comment by CAM-Gerlach** [comment]
Thanks for your helpful feedback, @jnsebgosselin 

> Also is this Windows 8 or 10? I think that would be better if it was done in 10.

8.1 Not sure how much this really matters other than the precise look of the title bar, but I have a test machine running 10 that I can get it set up on and take the screenshot there.

> Finally the fact that we see  `C:/Users/C. A. M. Gerlach/Documents/dev/SpyderDev` in the title bar of the main window, in the working dir. editbox and in the editor plugin title bar doesn't look professional.

Agreed. I was already planning on just remove it entirely for a cleaner look in Illustrator/Photoshop once the final screenshot etc. was decided upon (to avoid having to redo the whole thing if it changed). However, if we take it on my Windows 10 machine, I can just do it under a generically named user account as you suggest.

> My vote goes to default too

Okay then...I imagine you didn't have time, but any chance you could explain your reasoning behind this?

In any case...what counts as "default", aside from the syntax highlighting scheme (which I still strongly feel looks much better dark given the white theme of the website, but is sufficiently a matter of taste that I prepared a default Spyder theme version if others were insistent as mentioned previously)? Only the default ``temp.py`` file open? Only the default (Help?) pane as the selected tab in the top right, with the default "Usage" intro being shown? Strictly the default tabs open (one console bottom right, and Help/Variable explorer/File explorer top right), and no more not even in the background? Code style highlighting off? No plot or code shown in the console? No entries in the Variable explorer (if its even allowed to be the selected tab at all?) No breakpoints set? No CPU icon in the bottom right? No project explorer panel at all (since if not opened with a project, like on first run, it won't be there)? No split editor?

Along with the explicit question, I guess I'm making two points here: First, every one of these items demonstrates a specific Spyder feature, often a major one, and in some cases a significant advantage it holds over many similar IDEs. Second, the very fact that we have to ask this questions is a clue, in my viewpoint, of how arbitrary and capacious the distinction between "default" and "non-default" is, and why, in my viewpoint, it is not very meaningful or important in this context (*promotional*, i.e. attracting users to Spyder, not educating them on the default UI) at least when dealing with features built in to the program and easily accessible to the user.

In short, I don't see why we should be deliberately shooting ourselves in the foot when we're trying to make a crucial positive first impression to convince potential users to try Spyder, in order to ensure it continues to survive and thrive as an IDE. IMO.

> but with a slightly larger `project explorer` panel and a reduced width of the main window so there is less horiz. white space in the `editor`.

With my ideologueing out of the way, this would certainly be the way to go under the conditions that we are able to show the project explorer panel (even though it technically isn't "default" if a project isn't open, like on first run), but for whatever reason are barred from splitting the editor (a pretty big advantage of Spyder over Rstudio and several other IDEs IMO, and one of the main big things I like about Spyder vs. them). (Okay, almost all the ideologueing out of the way...now I'm done, I promise :) ) 

How about this as a pragmatic compromise: We take the version shown in my "Default" screenshot, split the editor, and widen the project pane a little (following your suggestion and what I had originally), while keeping the syntax highlighting/color scheme the default (from what I gather and had expected, the main point of disagreement). So something like this, except on Windows 10, with a generic user name, and the MainWindow code on the left?

image

**Comment by jnsebgosselin** [comment]
> In any case...what counts as "default"

"Default" as in how you named the 4 options you presented in your https://github.com/spyder-ide/website-spyder/pull/75#issuecomment-377593387

The last screenshot you posted looks good. I don't know about splitting the editor though. If it looks good on the website, why not. But the thing I'm afraid of is that it forces the width of the main window to be very large. So when the screenshot is matched with the banner, the text of the screenshot ends up very tiny. I'm not sure it is going to look good on the website.

Another idea: 
In the banner, for the name in full, you could also write `The Scientific Python IDE`, make the full name width fit with the Spyder name and center the banner with the screenshot.

**Comment by CAM-Gerlach** [comment]
> "Default" as in how you named the 4 options you presented in your https://github.com/spyder-ide/website-spyder/pull/75#issuecomment-377593387

Mmm, okay—thanks for clarifying @jnsebgosselin . That was my general working assumption, but I really was rather unsure.

> when the screenshot is matched with the banner, the text of the screenshot ends up very tiny. I'm not sure it is going to look good on the website.

Good point; I've been keeping an eye on the font size as well. My internal justification was that the actual content of the text is unimportant, and that the smaller size made it look more modern and refined, but I'm far from sold on that. Perhaps we could try splitting the panes vertically instead, and then increasing the editor font size and width of the side panes? 

We could just nix the split idea if that doesn't work out; its not the end of the world, but it is a pretty major Spyder feature over a lot of competitors for many people.

> In the banner, for the name in full, you could also write `The Scientific Python IDE`, make the full name width fit with the Spyder name and center the banner with the screenshot.

I seem to recall us trying something like that over in #6352 . @ccordoba12 what do you think? I guess one concern is how that (versus the full name) differentiates us from other nominally scientific python IDEs (Jupyterlab, Rodeo, etc).

**Comment by ccordoba12** [comment]
> The last screenshot you posted looks good. I don't know about splitting the editor though

That's also my main issue with your last screenshot @CAM-Gerlach. I think we should only show the Editor without splits. Other than that, it looks really cool!

> In any case...what counts as "default"

The default distribution of panes, with the default color scheme. The content you added looks really good and the project explorer on the left is fine too. It's not part of the default, but it looks nice.

> In short, I don't see why we should be deliberately shooting ourselves in the foot when we're trying to make a crucial positive first impression to convince potential users to try Spyder

We don't need to put *everything* in the screenshot. I think it's more like an appetizer. We could also have a dedicated *screenshots* section (inside our docs?) to show in more detail all Spyder has to offer. For example, what @andfoy did with our *Find in files* is terrific! It's so useful, especially on Windows, where it's not easy to install `ack` or `ag`.

> We could just nix the split idea if that doesn't work out; its not the end of the world, but it is a pretty major Spyder feature over a lot of competitors for many people.

I agree, but it's not easy for users to find because it's buried in the Options menu of the Editor. So we really need to find a better way to promote it (e.g. by adding it to the toolbar or the Source menu). Until then, the screenshot could confuse them.

>  @ccordoba12 what do you think?

I really like our current moto. Since our audience are scientists and engineers, they probably don't know what *IDE* means.

**Comment by CAM-Gerlach** [comment]
Thanks @ccordoba12 

> I think we should only show the Editor without splits.

Same rationale for that reason as @jnsebgosselin as well (insufficient space)? If so, then what about the vertical split I suggested? Or do you just have something against splits haha :)

> The default distribution of panes

Tell that to our last screenshot :)

> with the default color scheme

I figured I'd get overruled on that one...

>  We could also have a dedicated *screenshots* section (inside our docs?) to show in more detail all Spyder has to offer. 

We can have them in our docs

**Comment by CAM-Gerlach** [comment]
Thanks @ccordoba12 

> I think we should only show the Editor without splits.

Same rationale for that reason as @jnsebgosselin as well (insufficient space)? If so, then what about the vertical split I suggested? Or do you just have something against splits haha :)

Aside from that, I think we're in agreement after which I can go ahead, get my other machine up and running and grab the screenshot...and maybe a few different panel layouts/color schemes while we're at it, for other places in our site and "Overview" doc. 

Speaking of which, since (as I discuss below) we can use this and other screenshots across multiple platforms and we have a number of other image assets now (@jnsebgosselin 's banners, our core logo designs, various screenshots of Spyder and its panels/features, etc), we probably should have a centralized place (Google Drive, a repo, etc) to centrally store these images so the project members have easy access to them now and in the future. Or is there something like this already that I'm not aware of?

> The default distribution of panes

Tell that to our last screenshot :)

> with the default color scheme

I figured I'd get overruled on that one...

>  We could also have a dedicated *screenshots* section (inside our docs?) to show in more detail all Spyder has to offer. 

We certainly should have them in our docs too, but our website even more so since that's where we really want to show off the application front in center, rather than people having to dig through our docs for that. What I'd recommend is besides this "default" one (which we can use in our readme as well, and doc index page), perhaps 3 or so others that demonstrate different layouts, color schemes and panels open to show the range of Spyder's capabilities that we can spread across the main/overview pages of our site and the "Overview" page of our doc (and maybe scatter a few elsewhere as well), and then individual screenshots of the panels for their relevant pages of the doc and if we have subpages/sections for each feature on the site, we can include them there too. We do have some currently in our docs, but a lot are showing really dated UI chrome and some out of date features/lack thereof.

> I agree, but it's not easy for users to find because it's buried in the Options menu of the Editor.

It is harder than it could be, agreed, though it can also be more easily found by right-clicking anywhere along the tabs and title bar of the editor, or along the left or right margins. It didn't take me too long to find it. We should definitely include something actually saying how to use use it in our docs vs. just stating its presence as we do now—that's the thing with our docs right now; they actually seem more aimed at being an overview of the program's features that would be make more sense on our website, vs. the explanatory, instructional material that generally constitutes docs.

> I really like our current moto. Since our audience are scientists and engineers, they probably don't know what *IDE* means.

I indeed prefer the current one as well. I wouldn't go as far wrt to that second statement as an absolute—many certainly don't, but a good number likely does, and those that use Spyder (an IDE) or are likely to be interested in it are much more likely than the general population to be part of the latter group (after all, I am a scientist with minimal formal programming training, and I've known what was one since early undergraduate years). Still, I'd agree with keeping the current motto on the banner, as many don't, the concern I expressed above and that it just flows better, IMO.

**Comment by ccordoba12** [comment]
> Same rationale for that reason as @jnsebgosselin as well (insufficient space)?

No, just that it's part of our default setup and it's not easy to find right now.

> we probably should have a centralized place (Google Drive, a repo, etc)

Perhaps a Dropbox folder, since we're using Dropbox papers too.

> What I'd recommend is besides this "default" one (which we can use in our readme as well, and doc index page), perhaps 3 or so others that demonstrate different layouts, color schemes and panels open to show the range of Spyder's capabilities that we can spread across the main/overview pages of our site and the "Overview" page of our doc

Agreed.

**Comment by CAM-Gerlach** [comment]
> No, just that it's part of our default setup and it's not easy to find right now.

Alright, then. 

> Perhaps a Dropbox folder, since we're using Dropbox papers too.

Something to consider, though personally I've had a pretty poor experience with the free version of Dropbox particularly with regard to storing assets for organizations like this; the storage is an order of magnitude less space than Google Drive and counts toward that of every single user its shared with, which can get eaten up surprisingly quickly when dealing with the raw/original documents (especially photoshop PSDs/TIFFs) we'll want to put on there at some point), and overall some of the features and UI are more limited. But maybe they've gotten a lot better recently...

> Agreed.

So it's decided, it seems. I'll take:

* The requested main screenshot on the Windows 10 machine with the layout of the above, except with no split, a wider project and VarExp/Console pane, and a larger font size, and use that for this, the Readme, and the docs Index page. 

* Four or so others with different layouts, color schemes and panels open, and put them in the Overview page of the docs, and we can also think about where they could fit in the site

* Individual shots of each panel/feature for the docs, and possibly the website in the future.

**Comment by CAM-Gerlach** [comment]
BTW @ccordoba12 As part of the top bar is @dalthviz going to add on the right a download button linking to the Anaconda download page (similar in look to the current one for the source code buried down the page on a sub-tab), and secondarily a donate button linking to opencollective (like the one all the way at the buttom)? If not, should I create an new issue? Sorry for going a little off topic, but I don't want to create a duplicate issue if this is already getting done.

These have been the top two requests on our gitter and other sources regarding even the small number of people who found the old website (especially the download button), so IMO it should be our highest priority to add to the top bar in some form ASAP considering that without them, the website serves essentially no purpose right now as users have no way to actually download and use spyder, and existing users no way to support the project (nor access any useful documentation, nor any direct link to our main github repo which we should probably stick on the top bar as well, or at least somewhere prominent).

Right now, there is no link **whatsoever** to download the recommended Anaconda version, and the only download link there is, the source download one, is buried a page down and under a subtab (which only a very, very small fraction of potential new users would actually want—and of those that do actually want to download source, they are way more likely to want to do so through git rather than a plain zip/tar—though many may not be aware of it). Furthermore, the donate button requires the user to scroll all the way to the bottom of the page, which is far from easy to find. 

Therefore, is this in work or should I add a new issue about it? Furthermore, is the text along the top bar (especially when inactive) going to be made much darker? Its very hard to read or even notice as is. Thanks.

**Comment by ccordoba12** [comment]
> the storage is an order of magnitude less space than Google Drive

Right, then we should use Google Drive instead.

> So it's decided, it seems.

Agreed with all your points.

> As part of the top bar is @dalthviz going to add on the right a download button linking to the Anaconda download page (similar in look to the current one for the source code buried down the page on a sub-tab), and secondarily a donate button linking to opencollective (like the one all the way at the buttom)?

No, but you're right, we should add them to our navbar and also add special sections for them. Please open a new issue about it.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 @jnsebgosselin Alright, finally got everything setup on my other machine and took the shot—what do you all think now? I widened the panes, made the editor and console font 2 sizes bigger, and added an extra, cooler plot to the display, a generic username, as well as refining a few other things. On the other hand, it was taken on the machine's 1080p screen instead of one of my normal 1200p ones so it is less evenly proportioned which is probably not ideal. However, it isn't hard for me to hook it up to one of my proper monitors, realign everything and retake it so let me know if you'd prefer that.

Also, I'm still not 100% clear what I should do about the margins that the original had—remove them just on the bottom (as specifically requested, as as I did here), or on all sides? Thanks.

image

image

**Comment by CAM-Gerlach** [comment]
Actually, I just found out that the display of that test machine isn't 1080p like I thought, but 1600 x 900. I thought everything looked too small somehow, but I figured it was because of the default windows zoom setting or something that I changed long ago on my main machine.

In any case, I'll retake it with the machine connected to one of my primary monitors (I still have everything up), but:
* Should I keep the 16:9 aspect ratio of the above, or go for the more even full 16:10 of the previous?
* Should I make the window non-maximized so there's a more visible dark border around it as the past ones, or keep it maximized and borderless (will need to be 16:10 then unless I do some wizardry)? It looks significantly better with the border IMO...
* Not sure I'm a huge fan of the place I chose in the file being edited, even though it is rather symbolic. Thing I should should choose a different section? Or eschew that file entirely and use something with e.g. cells and more scientific/analysis code?
* Anything else I should change?

Thanks.

**Comment by CAM-Gerlach** [comment]
Updated as above. I added the outline viewer to fill the extra space, since I'd already extended the variable explorer/etc. column and the project explorer by quite a bit.

**Comment by ccordoba12** [comment]
> what do you all think now?

It looks really, really nice!! Thanks for listening to our suggestions! I'm going to merge right now to see how it looks live.

**Review by ccordoba12 — APPROVED** [review]

**Comment by ccordoba12** [comment]
The result is gorgeous!! Thanks a lot @CAM-Gerlach!

I scheduled several iteration sessions with @dalthviz this week to finish several little details, so I really hope the site will be ready by the end of this week, at most.

**Comment by CAM-Gerlach** [comment]
Thanks @ccordoba12 , so glad you like it! Now what would be *really* cool down the road is making it pseudo-interactive so users could explore more of the UI, by setting mouseover events for regions of the image corresponding to the various tabs, which would switch the panel that tab is attached two to show that tab. Not sure how hard that would be to set up, though...

This is also where it would be nice to have a development domain we could push to in order to test out changes before they go live in the future, as @goanpeca suggested—though it wouldn't be *too* hard to setup Travis to deploy the site on the ``gh-pages`` branch of our own repos, I'd think.

**Comment by jnsebgosselin** [comment]
Looks great, good job! It is sad we do not see it in full on the website though. We see only about a third of the figures.

Can you update the Readme also? The screenshot is very outdated there also.

**Comment by CAM-Gerlach** [comment]
@jnsebgosselin 

> It is sad we do not see it in full on the website though. We see only about a third of the figures.

Oh; thanks for letting me know. It looked perfect on my 16:10 monitors but I see it is cut off on 16:9—I'll submit a new PR with much less top margin and a modest additional margin on the bottom.

> Can you update the Readme also? The screenshot is very outdated there also.

Yup; I actually was in the middle of doing that right now; I'll update the one in the docs as well. This would basically a reincarnation of your spyder-ide/spyder#6352 , for which the banner was originally created in the first place.

**Pull request merged**
