### PR TITLE
PR: Change text color of footer to white to make it more visible

### PR DESCRIPTION
**Pull request by ccordoba12**
Also make bold the "Connect to us" font weight

### CODE REVIEW

**Comment by ccordoba12** [comment]
@dalthviz, please note the changes I'm doing here when making the footer PR in spyder-docs.

**Comment by CAM-Gerlach** [comment]
Good idea; as a suggestion you could apply the white color to just the "connect with us" line while leaving the credit lines as they are to further distinguish the two.

**Comment by CAM-Gerlach** [comment]
Oops, too late haha. Maybe you did it already; I didn't have time to check the CSS rules.

**Comment by ccordoba12** [comment]
Sorry, just merged this one. But changing to white also makes the copyright stuff look good:

seleccion_004

What makes the difference between the two is that *Connect to us* is in bold now.

**Comment by ccordoba12** [comment]
I think this looks much better than the previous footer, so let's merge it with production.

**Comment by CAM-Gerlach** [comment]
Yeah, after looking at it I agree with you on the white for the credit lines, 

The one other thing though along these lines is that the dark red links are really hard to read on the dark bg; dark bg + dark red is one of the lowest contrast/hardest to read combinations for the human eye. To get around this while still keeping our color scheme and the links distinctive, my mom (the retired graphic designer) did a quick mockup and suggested making the footer links white and bold (with the rest of the text not bold), and the pipes in between red (and bold) instead.

**Comment by ccordoba12** [comment]
> To get around this while still keeping our color scheme and the links distinctive, my mom (the retired graphic designer) did a quick mockup and suggested making the footer links white and bold (with the rest of the text not bold), and the pipes in between red (and bold) instead.

I also noticed the problems with red links. Your mom suggestion is very nice! I'll implement it right away.

**Pull request merged**
