### PR TITLE
Revert "PR: Add Spyder 3.3.1 release blog post"

### PR DESCRIPTION
**Pull request by ccordoba12**
Reverts spyder-ide/website-spyder#137.

@CAM-Gerlach, please resubmit this PR as a new one. Very sorry for this.

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
@ccordoba12 What's the trick? I made a new branch based on the previous 3.3.0 blog post branch, rebased that on the latest develop with the revert applied, and created a fresh pull request for my CAM-Gerlach/blog-release-3.3.0-redo branch against the spyder-ide/develop branch, but it still says "these two branches are identical" and won't let me submit it. What am I doing wrong?

**Comment by ccordoba12** [comment]
Did you remove your old branch?

**Comment by ccordoba12** [comment]
In your remote fork, I meant.

**Comment by CAM-Gerlach** [comment]
Yes; didn't change anything. I also redid the whole process again after you merged my other PR and rebased again, still didn't work. Finally just reverted the revert and submitted as #140 . It would probably have been easier and cleaner to just ``git reset`` the ``develop`` branch to just before the merge, as given it was such a tiny time interval the possibility of resulting conflicts would have been virtually nil, but perhaps there were reasons not to do that.

**Pull request merged**
