### PR TITLE
Upgrade to Lektor-Icon 3.x w/Bootstrap 5 & fix other issues

### PR DESCRIPTION
**Pull request by conradolandia**
This pull request aims to fix all the possible issues remaining in website-spyder after the last merge of Bootstrap 5 in lektor-icon.

### CODE REVIEW

**Review by CAM-Gerlach — COMMENTED** [review]
A few comments so far:

* [x] Seems like we're missing one `col-md-4` in the custom CSS, and might be worth double-checking for anything else that was missed (though nothing stood out to me inspecting the remaining selectors)
* [x] The layout and sizing of the plugins gallery items has substantial differences; the live site has its three items expand to fill the full column, while in this PR they remain the same size, and additionally in this PR the second has a large bottom margin, versus zero here. I'm not seeing any custom CSS or JS for this, so we probably missed it in the theme due to not carefully checking the case of N_gallery items % 4 not equal 0 with the final version at large sizes, which differs between the Spyder and demo sites.
* [x] Not sure how easily fixable it is here, but as a consequence of the impacts to Stellar with the theme changes, the hero graphic is scaled smaller and has much more bottom margin than before, which doesn't look as good.
* [x] The hero image change is unrelated to the theme changes, so it should be in a separate PR (like the logo change, etc)

**Comment by conradolandia** [comment]
Oh yeah, I'm not done yet.

**Comment by CAM-Gerlach** [comment]
Oh, oops—you'd marked this "Ready for Review", so I'd assumed it was ready sorry.

**Comment by conradolandia** [comment]
I should have left it as draft... my apologies.

**Comment by conradolandia** [comment]
This PR is ready for review, but requires merging of lektor-icon's [PR 29](https://github.com/spyder-ide/lektor-icon/pull/29) to be complete.

**Review by CAM-Gerlach — APPROVED** [review]
LGTM now, everything is fixed so I think we can merge this. Thanks @conradolandia !

**Pull request merged**
