### PR TITLE
Enhance footer and translate it using databags

### LINKED ISSUE #9: Enhance the footer (change template, add social media icons on footer)
Add social media icons for spyder-ide on the footer

twitter: spyder_ide
facebook: https://www.facebook.com/SpyderIDE/
google: https://plus.google.com/u/0/communities/112932801653352854842
github: https://github.com/spyder-ide/spyder
gitter:  https://gitter.im/spyder-ide/public

### LINKED ISSUE #22: Translate layout (nav bar, footer) using databags
https://www.getlektor.com/docs/content/databags/

### PR DESCRIPTION
**Pull request by rlaverde**
Fixes #9 
Fixes #22

### CODE REVIEW

**Comment by goanpeca** [comment]
Hmm we should be careful about this, cause the usual way of handling translations is to use `gettext` 

https://pypi.python.org/pypi/lektor-i18n/0.1

**Comment by rlaverde** [comment]
I'm not sure if lektor-i18n-plugin will be useful for translate footer and nav-bar, this plugin is used for translate content not templates, so It'll be necessary to move footer and o nav-bar to flowblocks, and It 'll be necessary to include these flowblocks over and over in all pages (I can't find another workaround)

Although this plugin will be useful when translating content pages, (I think we could include it for translate docs #19 and other pages #21) but for layout I think databags is better.

**Comment by goanpeca** [comment]
ok got it. but then we should start writing this somewhere maybe the wiki for now.

also we should include every plugin we use as part of the readme i think

**Comment by rlaverde** [comment]
> We should start writing this somewhere maybe the wiki for now.

Maybe a section in the website?

**Comment by goanpeca** [comment]
s section on the website on how to write website? very meta :-)

**Comment by rlaverde** [comment]
> a section on the website on how to write website? very meta :-)

I was thinking in a collaborate section, with different subpages: translate, develop... like [this wiki page](https://github.com/spyder-ide/spyder/wiki/Contributing-to-Spyder)

**Comment by goanpeca** [comment]
Ok, do you want to port stuff to the webpage?

**Comment by rlaverde** [comment]
> Ok, do you want to port stuff to the webpage?

Yes, but no for the first milestone (0.1.0).

@goanpeca  I think this is ready, what do you think?

**Review by goanpeca — APPROVED** [review]

**Comment by rlaverde** [comment]
Merging now, databags is the better option for i18n at the moment. I opened an issue for further discussing #41

**Pull request merged**
